/*--------------------------------------------------------------------------------------
 *  Copyright 2025 Glass Devtools, Inc. All rights reserved.
 *  Licensed under the Apache License, Version 2.0. See LICENSE.txt for more information.
 *--------------------------------------------------------------------------------------*/

/**
 * Query expansion / HyDE for the retrieval pipeline.
 *
 * Produces three views of the user's question:
 *   1. The raw text (original) — embedded as-is.
 *   2. Extracted code-flavored terms (terms) — joined and embedded.
 *   3. A short hypothetical-code snippet generated by the expander LLM (hyde)
 *      — embedded; tends to match real code style closely.
 *
 * The expander LLM defaults to a tiny local model (Qwen2.5-Coder-0.5B GGUF via
 * `node-llama-cpp`). Setting `v3code.semanticIndex.queryExpander = 'chat-model'`
 * routes through the user's configured chat model instead — useful when the
 * tiny model isn't available yet.
 *
 * Cached for 24h in the `query_cache` SQLite table to avoid hammering the
 * expander on every retrieval.
 */

import { sha256 } from './hashing.js';
import type { QueryExpansion } from './semanticIndexTypes.js';

const SYSTEM_PROMPT = `You expand short developer questions into search hints.
Output EXACTLY four lines, no other text:
TERMS: comma-separated identifiers, types, and APIs likely present in the answer.
CODE: a 3-8 line hypothetical code snippet (no fences) that would match the answer.
ALT1: one rephrasing focused on what the code does.
ALT2: one rephrasing focused on the symbol names involved.`;

export interface QueryExpanderApi {
	expand(prompt: string): Promise<QueryExpansion>;
	dispose?(): void;
}

export interface QueryExpanderOptions {
	/** Fired by the service when the user picks an expander. */
	mode: 'local-llama' | 'chat-model' | 'heuristic';
	/** Optional local-llama config — model path is lazy-downloaded. */
	llama?: { modelPath: string };
	/** Chat-model callback — the service injects a closure that wraps
	 *  `ISendLLMMessageService`. Keeps this file dep-free from workbench
	 *  services. */
	chatModelInvoke?: (system: string, user: string) => Promise<string>;
}

class LlamaExpander implements QueryExpanderApi {
	private session: any = null;
	private model: any = null;
	private context: any = null;
	private initPromise: Promise<void> | null = null;

	constructor(private readonly modelPath: string) {}

	private async init(): Promise<void> {
		if (this.session) return;
		if (!this.initPromise) {
			this.initPromise = (async () => {
				const llama: any = await import('node-llama-cpp' as any);
				this.model = new llama.LlamaModel({ modelPath: this.modelPath, gpuLayers: 0 });
				this.context = new llama.LlamaContext({ model: this.model, contextSize: 2048 });
				this.session = new llama.LlamaChatSession({ context: this.context, systemPrompt: SYSTEM_PROMPT });
			})();
		}
		await this.initPromise;
	}

	async expand(prompt: string): Promise<QueryExpansion> {
		await this.init();
		const raw = await this.session.prompt(prompt, { temperature: 0.2, maxTokens: 256 });
		return parseExpanderOutput(prompt, raw);
	}

	dispose(): void {
		// node-llama-cpp holds native GPU memory via the GGUF runtime — JS GC
		// does not free it. Explicit .dispose() on each handle is required to
		// release VRAM (~400MB for a small coder model).
		try { (this.session as any)?.dispose?.(); } catch { /* noop */ }
		try { (this.context as any)?.dispose?.(); } catch { /* noop */ }
		try { (this.model as any)?.dispose?.(); } catch { /* noop */ }
		this.session = null;
		this.context = null;
		this.model = null;
		this.initPromise = null;
	}
}

class ChatModelExpander implements QueryExpanderApi {
	constructor(private readonly invoke: (system: string, user: string) => Promise<string>) {}

	async expand(prompt: string): Promise<QueryExpansion> {
		const raw = await this.invoke(SYSTEM_PROMPT, prompt);
		return parseExpanderOutput(prompt, raw);
	}
}

/** Heuristic fallback used when the expander LLM is unavailable. */
class HeuristicExpander implements QueryExpanderApi {
	async expand(prompt: string): Promise<QueryExpansion> {
		return {
			original: prompt,
			codeTerms: extractIdentifiers(prompt),
			hypotheticalCode: '',
			alternatives: [],
		};
	}
}

export function createQueryExpander(opts: QueryExpanderOptions): QueryExpanderApi {
	if (opts.mode === 'local-llama' && opts.llama?.modelPath) {
		return new LlamaExpander(opts.llama.modelPath);
	}
	if (opts.mode === 'chat-model' && opts.chatModelInvoke) {
		return new ChatModelExpander(opts.chatModelInvoke);
	}
	// Both explicit 'heuristic' mode AND any other mode where the required
	// callback/model isn't available fall through here — heuristic is the
	// safe, always-available default.
	return new HeuristicExpander();
}

/** Stable cache key for a prompt — sha256 hex of the trimmed prompt. */
export function expansionCacheKey(prompt: string): string {
	return sha256(prompt.trim());
}

export function parseExpanderOutput(originalPrompt: string, raw: string): QueryExpansion {
	// The expander emits sections in a fixed order: TERMS → CODE → ALT1 → ALT2.
	// Each header MUST appear at column 0 on its own line (whitespace-only prefix
	// allowed). To prevent a code snippet that happens to contain `// TERMS: foo`
	// from prematurely closing the CODE section, each header is matched once and
	// in order — subsequent occurrences are treated as literal content.
	const lines = raw.split(/\r?\n/);
	const headerOrder = ['TERMS:', 'CODE:', 'ALT1:', 'ALT2:'] as const;
	type Header = typeof headerOrder[number];
	const sections: Record<Header, string[]> = { 'TERMS:': [], 'CODE:': [], 'ALT1:': [], 'ALT2:': [] };
	let currentIdx = -1;
	let seenIdx = -1;
	for (const line of lines) {
		const trimmed = line.replace(/^\s+/, '');
		// Only honour the next-expected header; everything else is content.
		const nextHeader = headerOrder[seenIdx + 1];
		if (nextHeader && trimmed.startsWith(nextHeader)) {
			seenIdx += 1;
			currentIdx = seenIdx;
			const rest = trimmed.slice(nextHeader.length).trim();
			if (rest) sections[nextHeader].push(rest);
			continue;
		}
		if (currentIdx >= 0) sections[headerOrder[currentIdx]].push(line);
	}
	const terms = sections['TERMS:'].join(' ').trim();
	const code = sections['CODE:'].join('\n').trim();
	const alt1 = sections['ALT1:'].join(' ').trim();
	const alt2 = sections['ALT2:'].join(' ').trim();
	return {
		original: originalPrompt,
		codeTerms: terms ? terms.split(',').map(t => t.trim()).filter(Boolean) : extractIdentifiers(originalPrompt),
		hypotheticalCode: code,
		alternatives: [alt1, alt2].filter(Boolean),
	};
}

// Stopword list — keeps short identifiers like `id`, `db`, `fs`, `os` (common
// in Go/Python/Node) while filtering English glue words that would flood the
// expansion. Tight curated set; expand cautiously.
const IDENT_STOPWORDS = new Set([
	'a', 'an', 'and', 'or', 'but', 'if', 'in', 'on', 'at', 'to', 'of', 'is', 'it', 'as', 'by', 'be',
	'for', 'the', 'this', 'that', 'these', 'those', 'with', 'from', 'into', 'over', 'under',
	'are', 'was', 'were', 'has', 'have', 'had', 'do', 'does', 'did', 'not', 'no', 'yes',
	'i', 'you', 'we', 'they', 'he', 'she', 'me', 'my', 'our', 'their',
	'will', 'would', 'should', 'could', 'can', 'may', 'might', 'must',
	'how', 'why', 'what', 'when', 'where', 'who', 'which',
	'so', 'than', 'then', 'just', 'also', 'about', 'like', 'such',
]);

const IDENT_RE = /[A-Za-z_][A-Za-z0-9_]*/g;
function extractIdentifiers(text: string): string[] {
	const seen = new Set<string>();
	const out: string[] = [];
	for (const m of text.matchAll(IDENT_RE)) {
		const tok = m[0];
		if (tok.length < 2) continue;
		if (IDENT_STOPWORDS.has(tok.toLowerCase())) continue;
		if (seen.has(tok)) continue;
		seen.add(tok);
		out.push(tok);
		if (out.length >= 12) break;
	}
	return out;
}
